import React, { useState, useMemo } from 'react';
import { ConfigModule, Currency } from '../types';
import { CURRENCY_RATES, BASE_SETUP_FEE_AED, RATE_PER_WEEK_AED } from '../constants';
import { 
  TrendingUp, 
  DollarSign, 
  Clock, 
  Users, 
  Building2, 
  Sparkles, 
  CheckCircle2, 
  ArrowUpRight, 
  Calculator,
  Sliders,
  HelpCircle
} from 'lucide-react';
import confetti from 'canvas-confetti';

interface ConfiguratorRoiCalculatorProps {
  modules: ConfigModule[];
  currentCurrency: Currency;
  totalWeeks: number;
  totalAED: number;
}

export const ConfiguratorRoiCalculator: React.FC<ConfiguratorRoiCalculatorProps> = ({
  modules,
  currentCurrency,
  totalWeeks,
  totalAED,
}) => {
  // Interactive Slider States
  const [hotelGuestsMonthly, setHotelGuestsMonthly] = useState<number>(40); // Guests in Fairmont / WTC per month
  const [clinicPatientsMonthly, setClinicPatientsMonthly] = useState<number>(75); // Resident outpatients per month
  const [checkupsMonthly, setCheckupsMonthly] = useState<number>(12); // Executive check-ups per month
  const [clinicMarginPercent, setClinicMarginPercent] = useState<number>(60); // Operating margin %

  // Check module multipliers
  const hasHotelConcierge = modules.some((m) => m.id === 'feat-hotel-concierge' && m.isSelected);
  const hasPortal = modules.some((m) => m.id === 'feat-portal' && m.isSelected);
  const hasAiTriage = modules.some((m) => m.id === 'feat-aitriage' && m.isSelected);
  const hasOrmFeedback = modules.some((m) => m.id === 'feat-orm-feedback' && m.isSelected);

  const formatPrice = (amountAED: number) => {
    if (currentCurrency === 'USD') return `$${Math.round(amountAED * CURRENCY_RATES.USD).toLocaleString('en-US')}`;
    if (currentCurrency === 'RUB') return `${Math.round(amountAED * CURRENCY_RATES.RUB).toLocaleString('ru-RU')} ₽`;
    return `${Math.round(amountAED).toLocaleString('en-US')} AED`;
  };

  // Calculations
  const metrics = useMemo(() => {
    // Average check by category (aligned with Dubai regional market benchmarks)
    const avgHotelCheckAED = 308; // Jet lag IV 300 + Room doctor visit 317
    const avgClinicCheckAED = 250; // GP + Ultrasound 233, Derma 225, ZO Skin 450
    const avgCheckupCheckAED = 800; // Executive checkup 360 (42 biomarkers + US + ECG)

    // Multipliers based on active modules
    let hotelMultiplier = hasHotelConcierge ? 1.35 : 1.0; // +35% traffic from concierge gateway
    let clinicMultiplier = 1.0;
    if (hasAiTriage) clinicMultiplier += 0.15; // +15% conversion from symptom triaging
    if (hasOrmFeedback) clinicMultiplier += 0.25; // +25% from 5.0 Google/2GIS rating recovery
    if (hasPortal) clinicMultiplier += 0.20; // +20% retention / repeat visits via EHR

    const effectiveHotelGuests = Math.round(hotelGuestsMonthly * hotelMultiplier);
    const effectiveClinicPatients = Math.round(clinicPatientsMonthly * clinicMultiplier);
    const effectiveCheckups = Math.round(checkupsMonthly * (hasPortal ? 1.25 : 1.0));

    // Gross Monthly Revenue generated by these channels
    const monthlyHotelRevenue = effectiveHotelGuests * avgHotelCheckAED;
    const monthlyClinicRevenue = effectiveClinicPatients * avgClinicCheckAED;
    const monthlyCheckupRevenue = effectiveCheckups * avgCheckupCheckAED;

    const totalMonthlyRevenueAED = monthlyHotelRevenue + monthlyClinicRevenue + monthlyCheckupRevenue;
    const totalMonthlyProfitAED = totalMonthlyRevenueAED * (clinicMarginPercent / 100);

    // Platform Attribution: estimated share of revenue directly unlocked by the digital platform
    const platformAttributedRevenueMonthly = totalMonthlyRevenueAED * 0.38; // 38% attribution
    const platformAttributedProfitMonthly = platformAttributedRevenueMonthly * (clinicMarginPercent / 100);

    // Payback period in months
    const paybackMonths = platformAttributedProfitMonthly > 0
      ? (totalAED / platformAttributedProfitMonthly)
      : 12;

    const paybackDays = Math.max(14, Math.round(paybackMonths * 30));

    // Annual Net Profit & ROI
    const annualAttributedProfitAED = platformAttributedProfitMonthly * 12;
    const netFirstYearProfitAED = annualAttributedProfitAED - totalAED;
    const roiPercentage = totalAED > 0
      ? Math.round((netFirstYearProfitAED / totalAED) * 100)
      : 500;

    // Fairmont Hotel 15% Referral Commission
    const hotelCommissionMonthlyAED = monthlyHotelRevenue * 0.15;
    const hotelCommissionAnnualAED = hotelCommissionMonthlyAED * 12;

    return {
      totalMonthlyRevenueAED,
      totalMonthlyProfitAED,
      platformAttributedProfitMonthly,
      paybackMonths: paybackMonths.toFixed(1),
      paybackDays,
      annualAttributedProfitAED,
      netFirstYearProfitAED,
      roiPercentage: Math.max(120, roiPercentage),
      hotelCommissionMonthlyAED,
      hotelCommissionAnnualAED,
      effectiveHotelGuests,
      effectiveClinicPatients,
    };
  }, [
    hotelGuestsMonthly,
    clinicPatientsMonthly,
    checkupsMonthly,
    clinicMarginPercent,
    hasHotelConcierge,
    hasPortal,
    hasAiTriage,
    hasOrmFeedback,
    totalAED,
  ]);

  const handleCelebrateRoi = () => {
    confetti({ particleCount: 50, spread: 60, origin: { y: 0.8 } });
  };

  return (
    <div className="bg-white p-7 sm:p-10 rounded-3xl border border-[#E2DFD7] shadow-sm space-y-10">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 border-b border-[#F1EDE6] pb-6">
        <div>
          <div className="text-[10px] font-semibold text-[#7FA9BC] uppercase tracking-widest mb-1.5 flex items-center gap-1.5">
            <Calculator className="w-3.5 h-3.5" />
            <span>Финансово-инвестиционная модель</span>
          </div>
          <h3 className="text-2xl sm:text-3xl font-serif text-[#222321] font-bold">
            ROI-калькулятор окупаемости платформы
          </h3>
          <p className="text-xs sm:text-sm text-[#747775] mt-1 max-w-2xl leading-relaxed">
            Прогноз возврата инвестиций для клиники Modern Medicine в отеле Fairmont Dubai (Suite 2105) 
            с учетом выбранных модулей ({modules.filter((m) => m.isSelected).length} мод., бюджет {formatPrice(totalAED)}).
          </p>
        </div>

        {/* Quick ROI Badge */}
        <div 
          onClick={handleCelebrateRoi}
          className="bg-[#222321] text-white px-5 py-3 rounded-2xl border border-white/10 shrink-0 text-center cursor-pointer hover:bg-black transition-colors shadow-sm"
        >
          <div className="text-[10px] uppercase font-semibold text-[#7FA9BC]">Прогноз окупаемости</div>
          <div className="text-2xl font-serif font-bold text-white mt-0.5">
            ~ {metrics.paybackDays} дней
          </div>
          <div className="text-[10px] text-emerald-400 font-medium">ROI 1-го года: +{metrics.roiPercentage}%</div>
        </div>
      </div>

      {/* Main Grid: Sliders on Left, ROI Results on Right */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Left Column: Interactive Flow Sliders */}
        <div className="lg:col-span-6 space-y-6 bg-[#F7F6F3] p-6 sm:p-7 rounded-2xl border border-[#E2DFD7]">
          <div className="flex items-center justify-between">
            <h4 className="text-sm font-semibold text-[#222321] flex items-center gap-2">
              <Sliders className="w-4 h-4 text-[#7FA9BC]" />
              <span>Параметры потока пациентов в Fairmont</span>
            </h4>
            <span className="text-[11px] text-[#747775]">Расчет за месяц</span>
          </div>

          {/* Slider 1: Fairmont & WTC Hotel Guests */}
          <div className="space-y-2">
            <div className="flex justify-between text-xs">
              <span className="font-medium text-[#222321]">
                Гости Fairmont & делегаты WTC (вызовы в номер):
              </span>
              <span className="font-bold text-[#222321]">
                {hotelGuestsMonthly} чел./мес.
              </span>
            </div>
            <input
              type="range"
              min="10"
              max="150"
              step="5"
              value={hotelGuestsMonthly}
              onChange={(e) => setHotelGuestsMonthly(Number(e.target.value))}
              className="w-full h-1.5 bg-[#E2DFD7] rounded-lg appearance-none cursor-pointer accent-[#222321]"
            />
            <div className="flex justify-between text-[10px] text-[#747775]">
              <span>Мин: 10</span>
              <span>Средний чек: ~900 AED (Jet Lag IV / Doctor)</span>
              <span>Макс: 150</span>
            </div>
          </div>

          {/* Slider 2: Outpatient Clinic Visits */}
          <div className="space-y-2">
            <div className="flex justify-between text-xs">
              <span className="font-medium text-[#222321]">
                Амбулаторные визиты в Suite 2105 (GP, УЗИ, Дерматология):
              </span>
              <span className="font-bold text-[#222321]">
                {clinicPatientsMonthly} визитов/мес.
              </span>
            </div>
            <input
              type="range"
              min="20"
              max="250"
              step="5"
              value={clinicPatientsMonthly}
              onChange={(e) => setClinicPatientsMonthly(Number(e.target.value))}
              className="w-full h-1.5 bg-[#E2DFD7] rounded-lg appearance-none cursor-pointer accent-[#222321]"
            />
            <div className="flex justify-between text-[10px] text-[#747775]">
              <span>Мин: 20</span>
              <span>Средний чек: ~650 AED</span>
              <span>Макс: 250</span>
            </div>
          </div>

          {/* Slider 3: Executive Check-up Packages */}
          <div className="space-y-2">
            <div className="flex justify-between text-xs">
              <span className="font-medium text-[#222321]">
                Executive Health Check-up 360° & Лонгевити:
              </span>
              <span className="font-bold text-[#222321]">
                {checkupsMonthly} пакетов/мес.
              </span>
            </div>
            <input
              type="range"
              min="5"
              max="60"
              step="1"
              value={checkupsMonthly}
              onChange={(e) => setCheckupsMonthly(Number(e.target.value))}
              className="w-full h-1.5 bg-[#E2DFD7] rounded-lg appearance-none cursor-pointer accent-[#222321]"
            />
            <div className="flex justify-between text-[10px] text-[#747775]">
              <span>Мин: 5</span>
              <span>Чек: 1,800 AED (УЗИ + 42 биомаркера)</span>
              <span>Макс: 60</span>
            </div>
          </div>

          {/* Multipliers Active Badges */}
          <div className="pt-2 border-t border-[#E2DFD7] space-y-2">
            <div className="text-[11px] font-semibold text-[#747775] uppercase">
              Активные усилители конверсии из ТЗ:
            </div>
            <div className="flex flex-wrap gap-1.5 text-[10px]">
              <span className={`px-2 py-0.5 rounded-full border ${hasHotelConcierge ? 'bg-[#DCEAF0] border-[#7FA9BC] text-[#222321] font-semibold' : 'bg-white/60 border-[#E2DFD7] text-[#747775] line-through'}`}>
                Fairmont Concierge (+35% в номер)
              </span>
              <span className={`px-2 py-0.5 rounded-full border ${hasPortal ? 'bg-[#DCEAF0] border-[#7FA9BC] text-[#222321] font-semibold' : 'bg-white/60 border-[#E2DFD7] text-[#747775] line-through'}`}>
                EHR Личный кабинет (+20% повторные визиты)
              </span>
              <span className={`px-2 py-0.5 rounded-full border ${hasAiTriage ? 'bg-[#DCEAF0] border-[#7FA9BC] text-[#222321] font-semibold' : 'bg-white/60 border-[#E2DFD7] text-[#747775] line-through'}`}>
                ИИ-Триаж (+15% конверсия)
              </span>
              <span className={`px-2 py-0.5 rounded-full border ${hasOrmFeedback ? 'bg-[#DCEAF0] border-[#7FA9BC] text-[#222321] font-semibold' : 'bg-white/60 border-[#E2DFD7] text-[#747775] line-through'}`}>
                ORM 5.0★ (+25% из карт)
              </span>
            </div>
          </div>

        </div>

        {/* Right Column: Key Economic Outputs */}
        <div className="lg:col-span-6 space-y-5">
          
          {/* Main 4 KPI Matrix */}
          <div className="grid grid-cols-2 gap-3.5">
            
            <div className="p-5 rounded-2xl bg-[#EFEDE8] border border-[#E2DFD7] space-y-1.5">
              <div className="text-[10px] font-bold text-[#747775] uppercase tracking-wider">
                Срок окупаемости
              </div>
              <div className="text-2xl sm:text-3xl font-serif font-bold text-[#222321]">
                {metrics.paybackDays} дн.
              </div>
              <div className="text-[11px] text-[#7FA9BC] font-medium">
                ~ {metrics.paybackMonths} месяца работы
              </div>
            </div>

            <div className="p-5 rounded-2xl bg-[#222321] text-white border border-[#222321] space-y-1.5">
              <div className="text-[10px] font-bold text-[#7FA9BC] uppercase tracking-wider">
                ROI первого года
              </div>
              <div className="text-2xl sm:text-3xl font-serif font-bold text-white">
                +{metrics.roiPercentage}%
              </div>
              <div className="text-[11px] text-emerald-400 font-medium">
                Возврат вложений {((metrics.annualAttributedProfitAED / totalAED) || 1).toFixed(1)}x
              </div>
            </div>

            <div className="p-5 rounded-2xl bg-[#F7F6F3] border border-[#E2DFD7] space-y-1.5">
              <div className="text-[10px] font-bold text-[#747775] uppercase tracking-wider">
                Выручка клиники / мес.
              </div>
              <div className="text-xl sm:text-2xl font-serif font-bold text-[#222321]">
                {formatPrice(metrics.totalMonthlyRevenueAED)}
              </div>
              <div className="text-[11px] text-[#747775]">
                Включая чекапы и вызовы
              </div>
            </div>

            <div className="p-5 rounded-2xl bg-[#F7F6F3] border border-[#E2DFD7] space-y-1.5">
              <div className="text-[10px] font-bold text-[#747775] uppercase tracking-wider">
                Чистая прибыль за 1-й год
              </div>
              <div className="text-xl sm:text-2xl font-serif font-bold text-emerald-800">
                +{formatPrice(metrics.netFirstYearProfitAED)}
              </div>
              <div className="text-[11px] text-emerald-700 font-medium">
                За вычетом бюджета ТЗ
              </div>
            </div>

          </div>

          {/* Hotel B2B Commission & Synergy Box */}
          <div className="p-5 rounded-2xl bg-white border border-[#7FA9BC] space-y-3 shadow-xs">
            <div className="flex items-center justify-between text-xs">
              <span className="font-serif font-bold text-base text-[#222321] flex items-center gap-1.5">
                <Building2 className="w-4 h-4 text-[#7FA9BC]" />
                <span>Non-Room Revenue для Fairmont Dubai (15%)</span>
              </span>
              <span className="text-[10px] bg-[#DCEAF0] text-[#222321] px-2 py-0.5 rounded-full font-medium">
                Zero CapEx
              </span>
            </div>

            <p className="text-xs text-[#747775] leading-relaxed">
              Благодаря отельному консьерж-шлюзу отель Fairmont Dubai получает <span className="font-semibold text-[#222321]">{formatPrice(metrics.hotelCommissionMonthlyAED)}/мес.</span> ({formatPrice(metrics.hotelCommissionAnnualAED)}/год) агентского дохода от направления гостей в Suite 2105. Это ключевой аргумент для переговоров с General Manager отеля.
            </p>
          </div>

          {/* Strategic Conclusion */}
          <div className="p-4 bg-[#EFEDE8] rounded-xl border border-[#E2DFD7] flex items-start gap-3 text-xs text-[#747775]">
            <CheckCircle2 className="w-4 h-4 text-emerald-700 shrink-0 mt-0.5" />
            <p>
              <strong className="text-[#222321]">Резюме для Елены Киреевой: </strong>
              Инвестиция в разработку платформы ({formatPrice(totalAED)}) окупается уже в первые недели коммерческой эксплуатации даже при консервативном потоке гостей отеля Fairmont.
            </p>
          </div>

        </div>

      </div>

    </div>
  );
};
