import { ConfigModule, ServiceItem, Doctor, Biomarker, Competitor, AudioTranscriptItem, MediaPlanItem, PodcastEpisode } from './types';

export const CURRENCY_RATES = {
  AED: 1,
  USD: 0.272,
  RUB: 26.5,
};

export const BASE_SETUP_FEE_AED = 5000;
export const RATE_PER_WEEK_AED = 1667;

export const INITIAL_MODULES: ConfigModule[] = [
  // Category 1: Core & DHA Compliance
  {
    id: 'feat-i18n',
    title: '3 Языка (RU / EN / AR)',
    description: 'Полная локализация интерфейса и поддержка RTL-верстки для арабского языка (стандарт DHA).',
    timeWeeks: 1.5,
    category: 'core',
    categoryLabel: 'Базовый функционал',
    highlight: 'DHA Стандарт',
    isSelected: true,
  },
  {
    id: 'feat-currency',
    title: 'Мультивалютный прайс (AED / USD / RUB)',
    description: 'Мгновенный автоматический пересчет цен для туристов из СНГ, Европы и резидентов ОАЭ.',
    timeWeeks: 0.5,
    category: 'core',
    categoryLabel: 'Базовый функционал',
    highlight: 'Автоконвертер',
    isSelected: true,
  },
  {
    id: 'feat-dha-compliance',
    title: 'Интеграция согласий NABIDH / DHA',
    description: 'Цифровые формы информированного согласия и протоколы защиты данных пациентов ОАЭ (PHI).',
    timeWeeks: 1.0,
    category: 'core',
    categoryLabel: 'Базовый функционал',
    highlight: 'Безопасность',
    isSelected: true,
  },

  // Category 2: Marketing & Conversion
  {
    id: 'feat-blog',
    title: 'Editorial Журнал врачей & Кейсы',
    description: 'Публикации статей, разборы клинических биомаркеров и экспертный блог для премиум SEO в Дубае.',
    timeWeeks: 1.0,
    category: 'marketing',
    categoryLabel: 'Маркетинг и Конверсия',
    highlight: 'SEO + Репутация',
    isSelected: true,
  },
  {
    id: 'feat-aitriage',
    title: 'ИИ-Триаж симптомов (Gemini AI)',
    description: 'Интеллектуальный ассистент первичного подбора врача и капельниц по свободному тексту.',
    timeWeeks: 1.0,
    category: 'marketing',
    categoryLabel: 'Маркетинг и Конверсия',
    highlight: 'AI Assistant',
    isSelected: true,
  },
  {
    id: 'feat-card-details',
    title: 'Микро-интерфейсы карточек услуг',
    description: 'Тайминги процедур, бейджи подготовки («Натощак»), аватары врачей и инфо о выезде в номер.',
    timeWeeks: 0.5,
    category: 'marketing',
    categoryLabel: 'Маркетинг и Конверсия',
    highlight: 'UX Детали',
    isSelected: true,
  },
  {
    id: 'feat-quickbook',
    title: 'Быстрая запись в WhatsApp в 1 клик',
    description: 'Генерация предзаполненного сообщения для регистратуры с кодом услуги и желаемым временем.',
    timeWeeks: 0.5,
    category: 'marketing',
    categoryLabel: 'Маркетинг и Конверсия',
    highlight: 'WhatsApp Direct',
    isSelected: true,
  },
  {
    id: 'feat-hotel-concierge',
    title: 'Шлюз B2B консьерж-сервиса Fairmont',
    description: 'Выделенный посадочный шлюз для консьержей и постояльцев Fairmont Dubai с прямым вызовом в номер за 15–30 мин.',
    timeWeeks: 1.0,
    category: 'marketing',
    categoryLabel: 'Маркетинг и Конверсия',
    highlight: 'Fairmont VIP 2105',
    isSelected: true,
  },
  {
    id: 'feat-orm-feedback',
    title: 'Антикризисный ORM (Сбор отзывов Google/2GIS)',
    description: 'Операционный модуль перехвата обратной связи на рецепции для быстрого вывода рейтинга из 1.0★ в 5.0★.',
    timeWeeks: 0.5,
    category: 'marketing',
    categoryLabel: 'Маркетинг и Конверсия',
    highlight: 'Рейтинг 5.0★',
    isSelected: true,
  },

  // Category 3: Patient Service & Portal
  {
    id: 'feat-portal',
    title: 'Личный кабинет пациента (EHR)',
    description: 'Защищенный доступ к истории визитов, назначениям врачей и PDF-заключениям анализов.',
    timeWeeks: 2.0,
    category: 'portal',
    categoryLabel: 'Пациентский сервис',
    highlight: 'EHR Portal',
    isSelected: true,
  },
  {
    id: 'feat-biomarkers',
    title: 'Интерактивные трекеры биомаркеров',
    description: 'Наглядные графики динамики ферритина, витамина D3, гормонов и эффекта от инфузионной терапии.',
    timeWeeks: 1.5,
    category: 'portal',
    categoryLabel: 'Пациентский сервис',
    highlight: 'Графики анализов',
    isSelected: true,
  },
  {
    id: 'feat-digital-intake',
    title: 'Digital Intake (Предварительный онбординг)',
    description: 'Дистанционное заполнение анамнеза и опросников до физического визита для устранения очередей.',
    timeWeeks: 1.0,
    category: 'portal',
    categoryLabel: 'Пациентский сервис',
    highlight: 'Pre-Check-in',
    isSelected: true,
  },
  {
    id: 'feat-burnout-protection',
    title: 'Защита врачей от выгорания (PACE-слоты)',
    description: 'Командный триаж сообщений администратором (снятие 26% нагрузки) и выделенные слоты в расписании.',
    timeWeeks: 0.5,
    category: 'portal',
    categoryLabel: 'Пациентский сервис',
    highlight: 'Work-Life Balance',
    isSelected: true,
  },

  // Category 4: Commerce & Payments
  {
    id: 'feat-payments',
    title: 'Онлайн-оплата Stripe & Apple Pay',
    description: 'Прием предоплаты, депозитов на дорогостоящие Check-Up программы и оплата процедур онлайн.',
    timeWeeks: 2.0,
    category: 'commerce',
    categoryLabel: 'E-Commerce & Оплата',
    highlight: 'Apple Pay & Card',
    isSelected: false,
  },
  {
    id: 'feat-tabby',
    title: 'Рассрочка BNPL (Tabby / Tamara)',
    description: 'Интеграция популярных в ОАЭ систем беспроцентной оплаты 4 частями для чеков от 1,000 AED.',
    timeWeeks: 1.5,
    category: 'commerce',
    categoryLabel: 'E-Commerce & Оплата',
    highlight: 'BNPL ОАЭ',
    isSelected: false,
  },
];

export const CLINIC_SERVICES: ServiceItem[] = [
  {
    id: 1,
    title: 'Прием ведущего гинеколога',
    category: 'aesthetics',
    priceAED: 225,
    duration: '45 мин',
    doctor: 'Д-р Ольга Димова',
    doctorRole: 'Aesthetic Medicine & Gynecology',
    badge: 'Консультация',
    prepNote: 'Желательно иметь результаты предыдущих анализов (УЗИ/мазки) при наличии.',
    description: 'Комплексный деликатный осмотр, сбор анамнеза, кольпоскопия и составление плана женского здоровья.',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 2,
    title: 'Прием терапевта (GP) и УЗИ-диагностика',
    category: 'wellness',
    priceAED: 233,
    duration: '45 мин',
    doctor: 'Д-р Николай Руденко',
    doctorRole: 'General Practitioner & Ultrasound Specialist DHA',
    badge: 'Терапия & УЗИ',
    prepNote: 'При исследовании брюшной полости — 4 часа не принимать пищу.',
    description: 'Комплексный осмотр врача общей практики, сбор анамнеза и ультразвуковое сканирование на оборудовании экспертного уровня.',
    image: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 3,
    title: 'Клинический протокол ZO Skin Health',
    category: 'aesthetics',
    priceAED: 450,
    duration: '60 мин',
    doctor: 'Д-р Ольга Димова',
    doctorRole: 'Aesthetic & Anti-Age Specialist',
    badge: 'Бестселлер',
    prepNote: 'Не использовать кислотные пилинги за 48 часов до посещения.',
    description: 'Индивидуальный дерматологический уход по протоколу Zein Obagi: эксфолиация, лифтинг, антиоксидантная защита.',
    image: 'https://images.unsplash.com/photo-1512290900672-1f55b9659f4d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 4,
    title: 'IV Therapy «Dubai Jetlag Recovery»',
    category: 'infusions',
    priceAED: 300,
    duration: '45 мин',
    doctor: 'Бригада Modern Medicine',
    doctorRole: 'Выездная медицинская служба',
    badge: 'В номере / дома',
    prepNote: 'Легкий прием пищи за 1-2 часа до начала процедуры.',
    description: 'Усиленный инфузионный коктейль с электролитами, магнием, глутатионом и витаминами группы B для акклиматизации.',
    image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 5,
    title: 'Комплексный Check-Up «Executive Health 360°»',
    category: 'diagnostics',
    priceAED: 800,
    duration: '120 мин',
    doctor: 'Консилиум врачей',
    doctorRole: 'Терапевт, Гинеколог/Уролог, УЗИ',
    badge: 'УЗИ в подарок',
    prepNote: 'Строго натощак (8-10 часов), разрешена только чистая вода.',
    description: 'Развернутый скрининг: 42 биомаркера, гормоны, ЭКГ, УЗИ брюшной полости и финальная беседа с главным врачом.',
    image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 6,
    title: 'Выезд врача и экспресс-анализы 24/7',
    category: 'wellness',
    priceAED: 317,
    duration: 'В течение 30 мин',
    doctor: 'Дежурный врач',
    doctorRole: 'Home & Hotel Doctor Care',
    badge: 'Fairmont & Дубай',
    prepNote: 'Прибытие специалиста в номер отеля Fairmont Dubai или частную резиденцию.',
    description: 'Осмотр на месте, экспресс-тесты, купирование острых состояний, назначение рецептов и капельниц.',
    image: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 7,
    title: 'Anti-Age Плазмотерапия PRP RegenLab',
    category: 'aesthetics',
    priceAED: 467,
    duration: '50 мин',
    doctor: 'Д-р Ольга Димова',
    doctorRole: 'Aesthetic Medicine',
    badge: 'Клеточный лифтинг',
    prepNote: 'Пить больше воды накануне процедуры. Не принимать аспирин.',
    description: 'Швейцарская запатентованная технология аутологичного клеточного омоложения кожи лица, шеи и зоны декольте.',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 8,
    title: 'Премиальный биохакинг: Инфузия NAD+',
    category: 'infusions',
    priceAED: 733,
    duration: '90 мин',
    doctor: 'Бригада Modern Medicine',
    doctorRole: 'Клеточная терапия',
    badge: 'Премиум Лонгевити',
    prepNote: 'Процедура проводится под контролем давления и пульса.',
    description: 'Митохондриальное перезагрузка: никотинамидадениндинуклеотид для ясности ума, омоложения ДНК и выносливости.',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 9,
    title: 'WTC / DWTC Delegate Express Energy Pass',
    category: 'infusions',
    priceAED: 250,
    duration: '45 мин',
    doctor: 'Выездная бригада Modern Medicine',
    doctorRole: 'DWTC Conference Support',
    badge: 'Для выставок WTC',
    prepNote: 'Экспресс-сессия до или после выставочного дня в Dubai World Trade Centre.',
    description: 'Специальный восстановительный протокол инфузий и кислородной поддержки для спикеров, делегатов и участников форумов в WTC.',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
  },
];

export const CLINIC_DOCTORS: Doctor[] = [
  {
    id: 'dr-olga',
    name: 'Д-р Ольга Димова',
    role: 'Aesthetic & Longevity Medicine Specialist',
    experience: '14+ лет клинической практики',
    quote: '«Истинное мастерство в медицине — это когда результат безупречен, а следы вмешательства абсолютно незаметны.»',
    avatarText: 'OD',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 'dr-nikolai',
    name: 'Д-р Николай Руденко',
    role: 'General Practitioner & Ultrasound Specialist DHA',
    experience: '16+ лет клинической практики',
    quote: '«Точная ранняя УЗИ-диагностика и системный контроль биомаркеров позволяют предотвратить до 80% острых состояний.»',
    avatarText: 'NR',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=600&q=80',
  },
];

export const PATIENT_BIOMARKERS: Biomarker[] = [
  {
    id: 'ferritin',
    name: 'Ферритин (Запас железа)',
    category: 'Энергетический баланс',
    unit: 'нг/мл',
    optimalRange: '40.0 - 150.0',
    currentValue: 68,
    status: 'optimal',
    history: [
      { date: 'Янв', value: 15 },
      { date: 'Март', value: 24 },
      { date: 'Май', value: 38 },
      { date: 'Июль', value: 55 },
      { date: 'Авг (Текущ)', value: 68 },
    ],
    clinicalNote: 'Отличный ответ на инфузионную терапию «Energy Boost». Уровень депо железа полностью восстановлен.',
  },
  {
    id: 'vit-d',
    name: 'Витамин D3 (25-OH)',
    category: 'Иммунитет & Гормоны',
    unit: 'нг/мл',
    optimalRange: '50.0 - 80.0',
    currentValue: 62,
    status: 'optimal',
    history: [
      { date: 'Янв', value: 20 },
      { date: 'Март', value: 29 },
      { date: 'Май', value: 44 },
      { date: 'Июль', value: 54 },
      { date: 'Авг (Текущ)', value: 62 },
    ],
    clinicalNote: 'Достигнут целевой диапазон для жителей Дубая с учетом пребывания в помещениях под кондиционером.',
  },
  {
    id: 'cortisol',
    name: 'Кортизол утренний',
    category: 'Стресс-маркер',
    unit: 'нмоль/л',
    optimalRange: '140 - 530',
    currentValue: 280,
    status: 'optimal',
    history: [
      { date: 'Янв', value: 580 },
      { date: 'Март', value: 490 },
      { date: 'Май', value: 360 },
      { date: 'Июль', value: 310 },
      { date: 'Авг (Текущ)', value: 280 },
    ],
    clinicalNote: 'Нормализация надпочечникового индекса после протокола нормализации сна и сеансов капельниц.',
  },
  {
    id: 'hemoglobin',
    name: 'Гемоглобин',
    category: 'Оксигенация тканей',
    unit: 'г/л',
    optimalRange: '120.0 - 150.0',
    currentValue: 134,
    status: 'optimal',
    history: [
      { date: 'Янв', value: 116 },
      { date: 'Март', value: 122 },
      { date: 'Май', value: 128 },
      { date: 'Июль', value: 132 },
      { date: 'Авг (Текущ)', value: 134 },
    ],
    clinicalNote: 'Стабильные нормативные показатели красной крови.',
  },
];

export const COMPETITORS_LIST: Competitor[] = [
  {
    id: 'modern-medicine',
    name: 'Modern Medicine Dubai',
    location: 'Fairmont Dubai, 21st Floor',
    rating: 1.0,
    reviewsCount: 14,
    insurancePlansCount: 25,
    keyFocus: 'GP, Гинекология, Дерматология, УЗИ, Выездной сервис',
    threatLevel: 'subject',
    threatLabel: 'Наш объект',
    pros: 'Престижная локация в Fairmont, виды с 21 этажа, опытные русскоязычные врачи.',
    cons: 'Критически низкий рейтинг Google (1.0★), отсутствие современного веб-позиционирования, слабое информирование гостей отеля.',
  },
  {
    id: 'ora-care',
    name: 'Ora Care Clinic',
    location: 'Fairmont Dubai, 1st Floor',
    rating: 5.0,
    reviewsCount: 280,
    insurancePlansCount: 32,
    keyFocus: 'Многопрофильная клиника, Стоматология, Косметология',
    threatLevel: 'threat-zero-km',
    threatLabel: 'Угроза 0-го км',
    pros: 'Идеальная проходимость на 1 этаже отеля, 5.0 звезд в Google, перехват всего отельного трафика.',
    cons: 'Высокая загруженность, отсутствие камерной приватности, очереди.',
  },
  {
    id: 'aster-szr',
    name: 'Aster Clinic SZR',
    location: 'Al Manal Tower, Sheikh Zayed Rd',
    rating: 4.7,
    reviewsCount: 1420,
    insurancePlansCount: 45,
    keyFocus: 'Масс-маркет SZR, Сетевая клиника, Страховая база',
    threatLevel: 'leader-szr',
    threatLabel: 'Лидер SZR',
    pros: 'Огромный поток за счет прямых договоров со всеми страховщиками ОАЭ.',
    cons: 'Конвейерный прием (10-15 минут на пациента), отсутствие премиального сервиса.',
  },
  {
    id: 'gms-clinic',
    name: 'GMS Clinic Dubai',
    location: 'Downtown / Business Bay',
    rating: 4.8,
    reviewsCount: 650,
    insurancePlansCount: 12,
    keyFocus: 'Доказательная медицина для экспатов СНГ и Европы',
    threatLevel: 'leader-cis',
    threatLabel: 'Лидер CIS',
    pros: 'Мощнейший бренд среди русскоязычных экспатов Дубая, высокие чеки, cash-pay модель.',
    cons: 'Высокая удаленность от северной части SZR, плотный лист ожидания.',
  },
  {
    id: 'hortman-clinic',
    name: 'Hortman Stem Cell Clinic',
    location: 'Burj Al Salam, SZR',
    rating: 4.9,
    reviewsCount: 410,
    insurancePlansCount: 5,
    keyFocus: 'Клеточная медицина, Anti-Age, VIP Чекапы',
    threatLevel: 'niche-luxury',
    threatLabel: 'Ультра-Премиум',
    pros: 'Роскошный интерьер, сильное позиционирование в нише долголетия.',
    cons: 'Чрезвычайно высокий порог входа (чеки от 5,000 AED).',
  },
];

export const PODCAST_TRANSCRIPT: AudioTranscriptItem[] = [
  {
    id: 1,
    speaker: 'Д-р Марк (NotebookLM Host)',
    time: '00:15',
    seconds: 15,
    text: 'Сегодня мы разбираем стратегический аудит для клиники Modern Medicine в Дубае. Самый поразительный факт — локация на 21 этаже легендарного отеля Fairmont на Sheikh Zayed Road.',
  },
  {
    id: 2,
    speaker: 'Сара (Healthcare Strategist)',
    time: '01:05',
    seconds: 65,
    text: 'Да, локация невероятная, но здесь кроется «парадокс отеля». На 1 этаже прямо в лобби сидит Ora Care с рейтингом 5.0 звезд, а у Modern Medicine в картах висит 1.0 звезда из-за старых отзывов. Обычный гость отеля просто не доезжает до 21 этажа.',
  },
  {
    id: 3,
    speaker: 'Д-р Марк (NotebookLM Host)',
    time: '02:30',
    seconds: 150,
    text: 'И именно поэтому Елена Киреева и ее команда должны строить не просто поликлинику у дома, а цифровую платформу целевого назначения — Destination Clinic. Цифровой личный кабинет, вызов медсестры прямо в номер люкса Fairmont и умный ИИ-триаж.',
  },
  {
    id: 4,
    speaker: 'Сара (Healthcare Strategist)',
    time: '04:10',
    seconds: 250,
    text: 'Точно! Дубайский рынок медицинского туризма сейчас перевалил за 1 миллиард дирхамов. Пациенты с Ближнего Востока и СНГ ценят приватность, персонализированные Check-up протоколы и четкую прозрачность цен в дирхамах, долларах и рублях.',
  },
  {
    id: 5,
    speaker: 'Д-р Марк (NotebookLM Host)',
    time: '06:00',
    seconds: 360,
    text: 'Новая модульная веб-платформа устраняет трение. Пациент в 1 клик описывает симптомы ИИ, видит свой маршрут, график восстановления ферритина в личном кабинете и подтверждает визит через WhatsApp консьержа.',
  },
];

export const FAIRMONT_B2B_PARTNERSHIP = {
  suiteLocation: 'Suite 2105, 21st Floor, Fairmont Dubai, Sheikh Zayed Road',
  hotelMedicalMenu: [
    {
      title: 'Jet Lag Recovery & Hydration IV Drips',
      category: 'Восстановительная инфузионная терапия',
      format: 'В номере гостя или в Suite 2105',
      time: '45 мин',
      priceAED: 283,
      description: 'Капельницы для гидратации, снятия усталости после длительных перелетов и подготовки к важным встречам.',
    },
    {
      title: '24/7 Room Visit (Doctor / Nurse on Call)',
      category: 'Круглосуточный вызов в номер отеля',
      format: 'В номер Fairmont за 15–30 минут',
      time: 'Круглосуточно',
      priceAED: 317,
      description: 'Выезд терапевта (GP) или медсестры прямо в номер для купирования недомоганий, экспресс-тестов и рецептов.',
    },
    {
      title: 'Executive Health Check-up 360°',
      category: 'Экспресс-диагностика здоровья',
      format: 'В клинике (Suite 2105) или с выездом',
      time: '60 мин',
      priceAED: 600,
      description: 'УЗИ-диагностика на портативном аппарате, забор биомаркеров (Ферритин, D3, Липиды) с цифровым отчетом в смартфон.',
    },
    {
      title: 'WTC / DWTC Delegate Express Energy Pass',
      category: 'Медицинское сопровождение конференций',
      format: 'Suite 2105 / В номер отеля',
      time: '45 мин',
      priceAED: 250,
      description: 'Специальный восстановительный протокол для спикеров, экспонентов и делегатов смежного World Trade Centre.',
    },
    {
      title: 'Urgent Dental & Dermatological Care',
      category: 'Неотложная помощь',
      format: 'Suite 2105 (21 этаж)',
      time: 'По звонку',
      priceAED: 200,
      description: 'Оперативный прием при острой зубной боли, солнечных ожогах кожи лица, экспресс-уход ZO Skin Health.',
    },
  ],
  commercialBenefits: [
    {
      title: 'Новый Non-Room Revenue для Fairmont',
      desc: 'Отель получает агентское вознаграждение от каждой направленной процедуры без каких-либо CapEx затрат.',
    },
    {
      title: 'Выделенный WhatsApp Concierge Desk',
      desc: 'Прямой закрытый чат для консьержей и службы Front Office для мгновенного заказа врача в 1 клик.',
    },
    {
      title: 'Многоязычный сервис (AR / EN / RU)',
      desc: 'Прием гостей на арабском, английском и русском языках без барьеров для туристов из стран GCC, Европы и СНГ.',
    },
    {
      title: 'VIP Fast-Track & Приватность',
      desc: 'Прием без очередей в приватном бутиковом офисе Suite 2105 с панорамным видом на Sheikh Zayed Road.',
    },
  ],
  coverLetterSample: {
    recipient: 'General Manager / Director of Hospitality / Front Office Manager, Fairmont Dubai',
    subject: 'Proposal B2B Partnership: VIP Concierge Medicine & In-Room Healthcare for Fairmont Dubai Guests (Suite 2105)',
    greeting: 'Dear General Manager / Executive Committee,',
    body: 'On behalf of Modern Medicine Medical Center, located directly within your hotel complex at Suite 2105 on the 21st floor, we would like to propose a strategic B2B partnership to establish an exclusive VIP Concierge Medicine service for guests at Fairmont Dubai. Our co-location presents a unique opportunity to transform medical support from an emergency hassle into a seamless 5-star amenity.',
  },
  phoneScript: {
    target: 'Head Concierge / Front Office Manager отеля Fairmont Dubai',
    elevatorPitch: 'Hello! I am calling from Modern Medicine Medical Center upstairs on the 21st floor (Suite 2105). We are launching an exclusive VIP Concierge Healthcare Service designed specifically for Fairmont Dubai guests and WTC event delegates: 24/7 room visits within 30 minutes, Jet Lag Recovery IV Drips, and complete privacy in Arabic, English, and Russian with zero investment from the hotel.',
    objections: [
      {
        objection: '«Отправьте материалы на общий Email»',
        response: 'I will definitely send it via email right away! May I double-check your direct WhatsApp or Email so I can also attach our contact card for instant emergency calls to Suite 2105?',
      },
      {
        objection: '«У нас уже есть медицинские контакты / скорая помощь»',
        response: 'We completely understand. Our focus is non-emergency 5-star care — like Jet Lag IV Therapy or 24/7 room visits within 30 minutes directly from the 21st floor, handled in Arabic, English, and Russian without long wait times.',
      },
    ],
  },
  rolloutRoadmap: [
    { week: 'Неделя 1', task: 'Подписание B2B SLA-соглашения, согласование прейскуранта и комиссионного вознаграждения.' },
    { week: 'Неделя 2', task: 'Брифинг консьерж-службы и Front Desk, передача брендированных QR-карт и настройка прямой WhatsApp-линии.' },
    { week: 'Неделя 3', task: 'Официальный запуск сервиса, старт 90-дневного пилотного периода и выездов в номера.' },
  ],
};

export const DOCTORS_MEDIA_PLAN: MediaPlanItem[] = [
  {
    week: 1,
    day: 'Пн (Reels / Short)',
    format: 'Экспертный Reels с графиками биомаркеров',
    topic: '«Почему в Дубае у всех падают Витамин D3 и Ферритин, даже если за окном +40°C?»',
    speaker: 'Д-р Николай Руденко (GP / Терапевт)',
    description: 'Короткий ролик с демонстрацией графиков анализов из Личного кабинета и объяснением влияния кондиционеров.',
    cta: 'Запишитесь на чек-ап биомаркеров в WhatsApp',
  },
  {
    week: 1,
    day: 'Ср (Telegram / Карусель)',
    format: 'Чек-лист в соцсетях',
    topic: '«Чек-лист восстановления после ночного перелета в Дубай (Jet Lag Recovery)»',
    speaker: 'Д-р Ольга Димова',
    description: 'Инфузионная терапия (IV Drip): как восстановить гидратацию и энергетический баланс за 45 минут.',
    cta: 'Доступен вызов медсестры или врача на дом/в отель 24/7',
  },
  {
    week: 2,
    day: 'Пн (Case Study)',
    format: 'Клинический разбор кейса',
    topic: '«Пациентка пришла с хронической усталостью: что показали анализы и как мы составили протокол»',
    speaker: 'Д-р Ольга Димова',
    description: 'Видеоразбор без персональных данных: от первичной консультации до динамики в медкарте EHR.',
    cta: 'Проверьте свои показатели — напишите администратору в WhatsApp',
  },
  {
    week: 2,
    day: 'Ср (Инфографика)',
    format: 'Карусель в соцсетях',
    topic: '«Пилинги и уход за кожей в условиях климата ОАЭ: что можно, а что строго запрещено»',
    speaker: 'Дерматолог клиники',
    description: 'Разбор безопасных протоколов ZO Skin Health by Zein Obagi при активном солнце.',
    cta: 'Консультация дерматолога в Suite 2105',
  },
  {
    week: 3,
    day: 'Пн (Reels / Short)',
    format: 'Видео-гид сервиса',
    topic: '«Как проходит визит врача на дом и в номер Fairmont? (Home Visit 24/7)»',
    speaker: 'Д-р Николай Руденко',
    description: 'Видеогид: от оформления заявки в 1 клик на сайте до приезда специалиста со всем портативным оборудованием.',
    cta: 'Сохраните наш WhatsApp для экстренного вызова врача 24/7',
  },
  {
    week: 4,
    day: 'Пн (Интервью)',
    format: 'Видео-интервью в клинике',
    topic: '«Почему европейские и СНГ-экспаты выбирают доказательную медицину в Fairmont Dubai»',
    speaker: 'Д-р Ольга Димова & Д-р Николай Руденко',
    description: 'Обсуждение стандартов доказательной медицины, отсутствия очередей и приватности в Suite 2105.',
    cta: 'Прямая связь с русскоязычным медицинским консьержем',
  },
];

export const PODCAST_SERIES: PodcastEpisode[] = [
  {
    id: 'podcast-market-risks',
    title: 'Что убивает медицинский бизнес в Дубае',
    subtitle: 'Анатомия ошибок клиник на Sheikh Zayed Road & DHA регуляторика',
    durationLabel: '7:42',
    category: 'Аудит рынка & Риски',
    contextTag: 'Исследование / Конкуренты',
    audioUrl: 'https://storage.googleapis.com/uspeshnyy-projects/modern_medicine/podcast/%D0%A7%D1%82%D0%BE_%D1%83%D0%B1%D0%B8%D0%B2%D0%B0%D0%B5%D1%82_%D0%BC%D0%B5%D0%B4%D0%B8%D1%86%D0%B8%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D0%B1%D0%B8%D0%B7%D0%BD%D0%B5%D1%81_%D0%B2_%D0%94%D1%83%D0%B1%D0%B0%D0%B5.m4a',
    description: 'Разбор ловушек страховой медицины Essential Benefits Plan (EBP), кассовых разрывов из-за 90-дневных задержек выплат от страховых, комиссий агрегаторов 20–35% и причин банкротства традиционных поликлиник в ОАЭ.',
    keyTopics: [
      'Ловушка EBP обязательного страхования в Дубае',
      'Драконовские комиссии агрегаторов (25–35%)',
      'Задержки выплат страховых компаний до 90 дней',
      'Почему побеждает модель Destination Clinic (Cash-Pay)'
    ]
  },
  {
    id: 'podcast-digital-strategy',
    title: 'Цифровая стратегия для премиальной клиники Дубая',
    subtitle: 'Архитектура веб-платформы, трилингвальность и FinTech',
    durationLabel: '8:55',
    category: 'IT-Архитектура & Web',
    contextTag: 'Конфигуратор & ТЗ',
    audioUrl: 'https://storage.googleapis.com/uspeshnyy-projects/modern_medicine/podcast/%D0%A6%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_%D0%B4%D0%BB%D1%8F_%D0%BF%D1%80%D0%B5%D0%BC%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B9_%D0%BA%D0%BB%D0%B8%D0%BD%D0%B8%D0%BA%D0%B8_%D0%94%D1%83%D0%B1%D0%B0%D1%8F.m4a',
    description: 'Стратегический разбор IT-экосистемы: скорость отклика < 1.5с на мобильном 5G, поддержка арабского RTL, интеграция безопасных шлюзов Stripe Apple Pay и рассрочки Tabby/Tamara без процентов.',
    keyTopics: [
      'Отказ от тяжелых legacy CMS в пользу React SPA',
      'Трилингвальный UX (RU / EN / AR) со стандартом DHA',
      'Беспроцентная рассрочка Tabby 4 частями для чеков >1000 AED',
      'Цифровые информированные согласия по нормам NABIDH'
    ]
  },
  {
    id: 'podcast-vip-fairmont',
    title: 'Цифровая стратегия Modern Medicine для VIP-пациентов',
    subtitle: 'B2B монетизация отеля Fairmont Dubai (Suite 2105)',
    durationLabel: '9:18',
    category: 'VIP & Отельный B2B',
    contextTag: 'Fairmont Suite 2105',
    audioUrl: 'https://storage.googleapis.com/uspeshnyy-projects/modern_medicine/podcast/%D0%A6%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%B0%D1%8F_%D1%81%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_Modern_Medicine_%D0%B4%D0%BB%D1%8F_VIP-%D0%BF%D0%B0%D1%86%D0%B8%D0%B5%D0%BD%D1%82%D0%BE%D0%B2.m4a',
    description: 'Как трансформировать присутствие на 21 этаже Fairmont Dubai в устойчивый канал выручки: консьерж-деск, выезд врача в номер за 20 минут, протоколы Jet Lag капельниц и конфиденциальность для резидентов ОАЭ.',
    keyTopics: [
      'Локация Suite 2105 как внеконкурентное преимущество',
      'Выездные мобильные медицинские бригады 24/7',
      'Партнерская интеграция с Front Office отеля (15% Non-Room Revenue)',
      'Обслуживание делегатов World Trade Centre (DWTC)'
    ]
  },
  {
    id: 'podcast-concierge-health',
    title: 'Личный цифровой консьерж здоровья Modern Medicine',
    subtitle: 'ИИ-триаж на Gemini, EHR личный кабинет и лояльность',
    durationLabel: '8:12',
    category: 'Пациентский сервис',
    contextTag: 'Прототип & EHR Портал',
    audioUrl: 'https://storage.googleapis.com/uspeshnyy-projects/modern_medicine/podcast/%D0%9B%D0%B8%D1%87%D0%BD%D1%8B%D0%B9_%D1%86%D0%B8%D1%84%D1%80%D0%BE%D0%B2%D0%BE%D0%B9_%D0%BA%D0%BE%D0%BD%D1%81%D1%8C%D0%B5%D1%80%D0%B6_%D0%B7%D0%B4%D0%BE%D1%80%D0%BE%D0%B2%D1%8C%D1%8F_Modern_Medicine.m4a',
    description: 'Умная маршрутизация пациента: свободный ввод симптомов на естественном языке, персональные рекомендации врачей клиники, визуализация лабораторных анализов и разгрузка докторов от рутины.',
    keyTopics: [
      'ИИ-триаж симптомов на базе Gemini 2.5 Flash',
      'Интерактивные графики ферритина и витамина D3',
      'PACE-слоты для защиты врачей от выгорания',
      '1-click подтверждение через русскоязычный WhatsApp'
    ]
  }
];
